# Generated by Django 5.1.1 on 2025-11-02 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="Category",
            new_name="category",
        ),
    ]
